---
- hosts: vagrant
  roles:
    - role: geerlingguy.docker
  become: true

  tasks:
    - name: vagrant user is added to the docker group
      user:
        name: vagrant
        group: docker
      register: user_result
      tags: [docker]